### ISSUE TITLE
Beeper Pin Polarity Reversed

### ISSUE THREAD

**Issue by partsdept** [hpsaturn/MultiFuncShield-Library#1]
Recently purchased a KNACRO brand MultiFunctionShield from Amazon.   The beeper would not turn off.

I reversed the default BEEPER_PIN state on line 78.   I also negated the value parameter in the three writeBeeper(byte value) functions, as there are three #ifdef, one for Leonardo, one for Uno, and one for Mega.

After that, everything worked ok.

**Comment by hpsaturn** [comment]
Thanks for report it, but I don't know what do, because in my MFS model works fine. Maybe if more users report this issue, maybe we need change it

**Comment by partsdept** [comment]
Hello Antonio,

I believe it might be a problem with the manufacturer.   Maybe they used
the wrong transistor between the pin and the beeper?   My friend bought the
same board and had the same problem.

https://www.amazon.com/KNACRO-Arduino-Multi-Function-Digital-Display/product-reviews/B01J9FDPVW/ref=cm_cr_dp_d_show_all_btm?ie=UTF8&reviewerType=all_reviews

There are some other Amazon customers that have the same problem.   I left
feedback on the Amazon page as well.

Thank you for hosting the library on GitHub.

John

**Comment by hpsaturn** [comment]
Maybe you can do a pull request with a method for config that? something like that:

```cpp
MFS.setBeepReversePolarity(bool enable)
```

and maybe submit too a example?

**Comment by partsdept** [comment]
Hello Antonio,

I am somewhat new to using features on GitHub on larger projects.  I will
look into how to do a Pull Request properly and I will submit this to help
the community that has been purchasing the MFS shields with the reversed
transistors.

How would you get these changes back to the company in the UK where people
can still download the library directly?    Are you in touch with them?

Talk soon,

John

**Comment by hpsaturn** [comment]
Maybe the next guide can help you to understand how to make a `pull request`:

https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github

With your question, I don't understand it. Please clarify better it.

Thanks.

**Comment by hpsaturn** [comment]
this issue was fixed on PR #3
