### ISSUE TITLE
Unable to send pull request without change entire file

### ISSUE THREAD

**Issue by hugodopradofernandes** [hpsaturn/MultiFuncShield-Library#5]
Unable to send pull request without change entire file

Right after click to edit the file, I receive the message on Github:
 _We’ve detected the file has mixed line endings. When you commit changes we will normalize them to Windows-style (CRLF)._

Then once I save, entire fille will be marked as modified.
Then pls change the file yourself.
Here are the change proposal I have. Please add them to the file here on github, then it will fix also line endings.

File: **MultiFuncShield.cpp**

------------------

**Line 16: change chars K,M,V,W,Z chars to differentiate them instead of show 3 bars. Based on representations from https://en.wikipedia.org/wiki/Seven-segment_display_character_representations**

`const byte SEGMENT_MAP_ALPHA[] = {136, 131, 167, 161, 134, 142, 144, 139 ,207, 241, 138, 199, 170, 171, 163, 140, 152, 175, 146, 135, 227, 227, 129, 137, 145, 164};`

------------------

**Line 958: add more chars: ? ! ' "**

      case '?':
        segmentValue = 172;
        break;
      case '!':
        segmentValue = 121;
        break;
      case '\'':
        segmentValue = 253;
        break;
      case '"':
        segmentValue = 221;
        break;

**Comment by hpsaturn** [comment]
Please make again the pull request, because is your contribution. I already fixed endline issue with dos2unix command on my Debian. Please try again the PR
